### ISSUE TITLE
Maven dependency?

### ISSUE THREAD

**Issue by Anonymous-Coward** [ThomasKrieger/concurrent-junit#1]
Since very many Java projects are built using maven, it would be useful to have this in a public maven repo too.

**Comment by ThomasKrieger** [comment]
Hi @Anonymous-Coward,
i will add concurrent-junit to a maven repo. Thank you for your comment.

As soon as I make progress in this area, I will post back here.

Cheers,
Thomas

**Comment by ethlo** [comment]
Anything happening with regards to maven central?

**Comment by ThomasKrieger** [comment]
Hi,

I uploaded the files to maven central.
The maven dependency is:
<dependency>
<groupId>com.vmlens</groupId>
<artifactId>concurrent-junit</artifactId>
<version>1.0.0</version>
</dependency>

Regards
Thomas
