### ISSUE TITLE
ConcurrentTestRunner running the code but saying 0 tests run

### ISSUE THREAD

**Issue by kishore25kumar** [ThomasKrieger/concurrent-junit#2]
Hi,

I am using ConcurrentTestRunner. The code is running but it says 0 tests ran. I am using junit4.12. Any idea for this issue?

**Comment by ThomasKrieger** [comment]
Hi.

from which tool do you run your test, eclipse, Intellij, maven,...? It might be related to timeout of the test runner.

Best Regards
Thomas

**Comment by kishore25kumar** [comment]
I am running it using IntelliJ IDE

**Comment by romain-grecourt** [comment]
Hi, same issue here.

Using Maven, JUnit 4.12 .

 mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/share/apache-maven-3.3.9
Java version: 9-ea, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: en_US, platform encoding: US-ASCII
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

**Comment by necrosisbb** [comment]
I found adding this 

`                 for( EachTestNotifier eachTestNotifier :   eachTestNotifierList ) {
                     eachTestNotifier.fireTestFinished();
                 }
`

to the end of the `private void runChildrenConcurrently(final RunNotifier notifier)` method solved the problem on successful tests, it seems like the code was calling fireTestStarted but not fireTestFinished

**Comment by ThomasKrieger** [comment]
Hi, thanks for the fix. I added it and released a new version (1.0.2)
