### ISSUE TITLE
ConcurrentTestRunner not notifying passed tests on intellij

### ISSUE THREAD

**Issue by lfsanchezg** [ThomasKrieger/concurrent-junit#3]
Hi, I started using your lib today and noticed that IntelliJ doesn't shows the tests results well after using ConcurrentTestRunner. I ran this

```java
@RunWith(ConcurrentTestRunner.class)
public class TestingTests
{

	@Test
	public void thisShouldPass()
	{
		Assert.assertTrue(true);
	}
	@Test
	public void thisShouldFail()
	{
		Assert.fail();
	}
}
```
And got this:
![Current behaviour](https://cloud.githubusercontent.com/assets/4084015/20892775/3f9b159c-baee-11e6-9864-174418bc8eb7.PNG)

If I remove the @RunWith annotation for using the default runner, I get the expected behaviour:

![Expected behaviour](https://cloud.githubusercontent.com/assets/4084015/20892811/586c1fc6-baee-11e6-90ad-952722f23b10.PNG)

Any ideas on this? I'm using Junit 4.12, Java 8 and IntelliJ 2016.2

Best regards
Luis.

**Comment by ThomasKrieger** [comment]
same as issue 2
